### ISSUE TITLE
Feature Request: From readme commands to bash scripts

### ISSUE THREAD

**Issue by xet7** [walkero-gr/dde4aros#1]
Hi,
you have some commands at readme that require copy-paste.

Can you add those to repos as bash scipts, so they are available inside or outside of Docker container, depending where those commands are planned to be used.

For example:
```
build-aros.sh
```
And then simplify readme so that those scripts are used there instead.

**Comment by xet7** [comment]
And set those scripts as executeable:
```
chmod +x *.sh
```
Then commit to repo

**Comment by walkero-gr** [comment]
Thank you for your comment.
Actually those commands are not even needed to be used, if someone does not need to compile AROS. These are only an example. Since AROS is possible to be compiled, I guess that people can use this docker image to build their own software for AROS.

**Comment by xet7** [comment]
Hmm, actually those are just couple of commands, it's good that they are visible at readme.

**Comment by walkero-gr** [comment]
Updated the readme to make it even more clear.
