### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by xet7** [walkero-gr/dde4aros#2]
Following those build steps, this gets stuck:
```
root@93086566a268:/usr/src# make -j 2 bootiso-quick
env: '/usr/src/bin/linux-x86_64/tools/mmake': No such file or directory
make: *** [Makefile:325: bootiso-quick] Error 127
```

**Comment by walkero-gr** [comment]
Please, try that again, by pulling the new image. I did some updates yesterday and managed to complete the whole AROS compilation process. I also got a new ISO built, which I didn't manage to test boot yet.
To pull the newest image please do
`docker pull walkero/dde4aros:latest`

**Comment by xet7** [comment]
I [deleted all docker data](https://github.com/wekan/docker-cleanup-volumes) and I still get the same error:
```
root@6ddadaa569e4:/usr/src# make -j 2 bootiso-quick
env: '/usr/src/bin/linux-x86_64/tools/mmake': No such file or directory
make: *** [Makefile:325: bootiso-quick] Error 127
root@6ddadaa569e4:/usr/src# exit  
exit
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
walkero/dde4aros    latest              989c868b8a10        10 hours ago    
```
I tried to build Docker image myself:
```
cd dde4aros
git pull
docker build -t dde .
cd ../AROS
git pull
docker run -it --rm --name ddetest -v "$PWD":/usr/src -w /usr/src dde:latest
./configure --target=pc-x86_64 --enable-ccache --with-gcc-version=9.1.0 --with-binutils-version=2.32 --with-portssources=/usr/src/AROS
$ make -j 2 bootiso-quick
env: '/usr/src/bin/linux-x86_64/tools/mmake': No such file or directory
make: *** [Makefile:325: bootiso-quick] Error 127
```
I can't get it working.

**Comment by walkero-gr** [comment]
Let me check it again... and will be back to you. Maybe a package is missing...

**Comment by walkero-gr** [comment]
Can you please check it again and see if it works now? 
Pull the new image with
`docker pull walkero/dde4aros:latest`

**Comment by xet7** [comment]
Now it started compiling without error. I'll wait it to finish.

**Comment by xet7** [comment]
Anyway, this error is already fixed.

**Comment by walkero-gr** [comment]
If you find any more issues come back and tell me. I am interested to make it as good as I can. Please check also my apignosis app (https://bitbucket.org/walkero/apignosis/wiki/Home), an autodock viewer for all major platforms.
